# Generated by Django 5.0.3 on 2024-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='remeras/')),
                ('marca', models.CharField(max_length=50)),
                ('talle', models.IntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')])),
                ('color', models.CharField(max_length=50)),
                ('lisa', models.BooleanField(default=True)),
                ('genero', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Unisex')])),
            ],
        ),
    ]
